//
//  Languaje.swift
//  whisper.swiftui
//
//  Created by Rubén García Hernando on 26/8/23.
//

import Foundation

enum Language: Int {
    case english = 0, chinese = 1, german = 2, spanish = 3, russian = 4, korean = 5, french = 6, japanese = 7,
    portuguese = 8, turkish = 9, polish = 10, catalan = 11, dutch = 12, arabic = 13, swedish = 14, italian = 15,
    indonesian = 16, hindi = 17, finnish = 18, vietnamese = 19, hebrew = 20, ukrainian = 21, greek = 22, malay = 23,
    czech = 24, romanian = 25, danish = 26, hungarian = 27, tamil = 28, norwegian = 29, thai = 30, urdu = 31,
    croatian = 32, bulgarian = 33, lithuanian = 34, latin = 35, maori = 36, malayalam = 37, welsh = 38, slovak = 39,
    telugu = 40, persian = 41, latvian = 42, bengali = 43, serbian = 44, azerbaijani = 45, slovenian = 46, kannada = 47,
    estonian = 48, macedonian = 49, breton = 50, basque = 51, icelandic = 52, armenian = 53, nepali = 54, mongolian = 55,
    bosnian = 56, kazakh = 57, albanian = 58, swahili = 59, galician = 60, marathi = 61, punjabi = 62, sinhala = 63,
    khmer = 64, shona = 65, yoruba = 66, somali = 67, afrikaans = 68, occitan = 69, georgian = 70, belarusian = 71,
    tajik = 72, sindhi = 73, gujarati = 74, amharic = 75, yiddish = 76, lao = 77, uzbek = 78, faroese = 79,
    haitianCreole = 80, pashto = 81, turkmen = 82, nynorsk = 83, maltese = 84, sanskrit = 85, luxembourgish = 86,
    myanmar = 87, tibetan = 88, tagalog = 89, malagasy = 90, assamese = 91, tatar = 92, hawaiian = 93, lingala = 94,
    hausa = 95, bashkir = 96, javanese = 97, sundanese = 98

    var code: String {
        switch self {
        case .english: return "en"
        case .chinese: return "zh"
        case .german: return "de"
        case .spanish: return "es"
        case .russian: return "ru"
        case .korean: return "ko"
        case .french: return "fr"
        case .japanese: return "ja"
        case .portuguese: return "pt"
        case .turkish: return "tr"
        case .polish: return "pl"
        case .catalan: return "ca"
        case .dutch: return "nl"
        case .arabic: return "ar"
        case .swedish: return "sv"
        case .italian: return "it"
        case .indonesian: return "id"
        case .hindi: return "hi"
        case .finnish: return "fi"
        case .vietnamese: return "vi"
        case .hebrew: return "he"
        case .ukrainian: return "uk"
        case .greek: return "el"
        case .malay: return "ms"
        case .czech: return "cs"
        case .romanian: return "ro"
        case .danish: return "da"
        case .hungarian: return "hu"
        case .tamil: return "ta"
        case .norwegian: return "no"
        case .thai: return "th"
        case .urdu: return "ur"
        case .croatian: return "hr"
        case .bulgarian: return "bg"
        case .lithuanian: return "lt"
        case .latin: return "la"
        case .maori: return "mi"
        case .malayalam: return "ml"
        case .welsh: return "cy"
        case .slovak: return "sk"
        case .telugu: return "te"
        case .persian: return "fa"
        case .latvian: return "lv"
        case .bengali: return "bn"
        case .serbian: return "sr"
        case .azerbaijani: return "az"
        case .slovenian: return "sl"
        case .kannada: return "kn"
        case .estonian: return "et"
        case .macedonian: return "mk"
        case .breton: return "br"
        case .basque: return "eu"
        case .icelandic: return "is"
        case .armenian: return "hy"
        case .nepali: return "ne"
        case .mongolian: return "mn"
        case .bosnian: return "bs"
        case .kazakh: return "kk"
        case .albanian: return "sq"
        case .swahili: return "sw"
        case .galician: return "gl"
        case .marathi: return "mr"
        case .punjabi: return "pa"
        case .sinhala: return "si"
        case .khmer: return "km"
        case .shona: return "sn"
        case .yoruba: return "yo"
        case .somali: return "so"
        case .afrikaans: return "af"
        case .occitan: return "oc"
        case .georgian: return "ka"
        case .belarusian: return "be"
        case .tajik: return "tg"
        case .sindhi: return "sd"
        case .gujarati: return "gu"
        case .amharic: return "am"
        case .yiddish: return "yi"
        case .lao: return "lo"
        case .uzbek: return "uz"
        case .faroese: return "fo"
        case .haitianCreole: return "ht"
        case .pashto: return "ps"
        case .turkmen: return "tk"
        case .nynorsk: return "nn"
        case .maltese: return "mt"
        case .sanskrit: return "sa"
        case .luxembourgish: return "lb"
        case .myanmar: return "my"
        case .tibetan: return "bo"
        case .tagalog: return "tl"
        case .malagasy: return "mg"
        case .assamese: return "as"
        case .tatar: return "tt"
        case .hawaiian: return "haw"
        case .lingala: return "ln"
        case .hausa: return "ha"
        case .bashkir: return "ba"
        case .javanese: return "jv"
        case .sundanese: return "su"
        }
    }
}

extension Language {
    var name: String {
        switch self {
        case .english: return "English"
        case .chinese: return "Chinese"
        case .german: return "German"
        case .spanish: return "Spanish"
        case .russian: return "Russian"
        case .korean: return "Korean"
        case .french: return "French"
        case .japanese: return "Japanese"
        case .portuguese: return "Portuguese"
        case .turkish: return "Turkish"
        case .polish: return "Polish"
        case .catalan: return "Catalan"
        case .dutch: return "Dutch"
        case .arabic: return "Arabic"
        case .swedish: return "Swedish"
        case .italian: return "Italian"
        case .indonesian: return "Indonesian"
        case .hindi: return "Hindi"
        case .finnish: return "Finnish"
        case .vietnamese: return "Vietnamese"
        case .hebrew: return "Hebrew"
        case .ukrainian: return "Ukrainian"
        case .greek: return "Greek"
        case .malay: return "Malay"
        case .czech: return "Czech"
        case .romanian: return "Romanian"
        case .danish: return "Danish"
        case .hungarian: return "Hungarian"
        case .tamil: return "Tamil"
        case .norwegian: return "Norwegian"
        case .thai: return "Thai"
        case .urdu: return "Urdu"
        case .croatian: return "Croatian"
        case .bulgarian: return "Bulgarian"
        case .lithuanian: return "Lithuanian"
        case .latin: return "Latin"
        case .maori: return "Maori"
        case .malayalam: return "Malayalam"
        case .welsh: return "Welsh"
        case .slovak: return "Slovak"
        case .telugu: return "Telugu"
        case .persian: return "Persian"
        case .latvian: return "Latvian"
        case .bengali: return "Bengali"
        case .serbian: return "Serbian"
        case .azerbaijani: return "Azerbaijani"
        case .slovenian: return "Slovenian"
        case .kannada: return "Kannada"
        case .estonian: return "Estonian"
        case .macedonian: return "Macedonian"
        case .breton: return "Breton"
        case .basque: return "Basque"
        case .icelandic: return "Icelandic"
        case .armenian: return "Armenian"
        case .nepali: return "Nepali"
        case .mongolian: return "Mongolian"
        case .bosnian: return "Bosnian"
        case .kazakh: return "Kazakh"
        case .albanian: return "Albanian"
        case .swahili: return "Swahili"
        case .galician: return "Galician"
        case .marathi: return "Marathi"
        case .punjabi: return "Punjabi"
        case .sinhala: return "Sinhala"
        case .khmer: return "Khmer"
        case .shona: return "Shona"
        case .yoruba: return "Yoruba"
        case .somali: return "Somali"
        case .afrikaans: return "Afrikaans"
        case .occitan: return "Occitan"
        case .georgian: return "Georgian"
        case .belarusian: return "Belarusian"
        case .tajik: return "Tajik"
        case .sindhi: return "Sindhi"
        case .gujarati: return "Gujarati"
        case .amharic: return "Amharic"
        case .yiddish: return "Yiddish"
        case .lao: return "Lao"
        case .uzbek: return "Uzbek"
        case .faroese: return "Faroese"
        case .haitianCreole: return "Haitian Creole"
        case .pashto: return "Pashto"
        case .turkmen: return "Turkmen"
        case .nynorsk: return "Nynorsk"
        case .maltese: return "Maltese"
        case .sanskrit: return "Sanskrit"
        case .luxembourgish: return "Luxembourgish"
        case .myanmar: return "Myanmar"
        case .tibetan: return "Tibetan"
        case .tagalog: return "Tagalog"
        case .malagasy: return "Malagasy"
        case .assamese: return "Assamese"
        case .tatar: return "Tatar"
        case .hawaiian: return "Hawaiian"
        case .lingala: return "Lingala"
        case .hausa: return "Hausa"
        case .bashkir: return "Bashkir"
        case .javanese: return "Javanese"
        case .sundanese: return "Sundanese"
        }
    }
}
